[custom.all.tensortype]
type = "local"
path = ""
ipkg = "tensortype.ipkg"
test = "tests/tensortype-tests.ipkg"

[custom.all.tensortype-examples]
type = "local"
path = "examples"
ipkg = "tensortype-examples.ipkg"